name: flutter_chat_list_view
description: ChatListView is a listview designed for IM usage. 
version: 0.0.1
author: JimmyTai
homepage: https://github.com/JimmyTai

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.5

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter